env: local
http:
  port: 8000
data:
  sqlite:
    filename: storage/sqlite.db

log:
  log_level: debug
  encoding: console # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
